ko_fi: reecem # Replace with a single Ko-fi username
custom: ['https://www.paypal.me/iexistin3d', 'https://www.buymeacoffee.com/ReeceM'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
